sudo: false
language: node_js
node_js:
  - 6.13.4
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - hexo clean
  - hexo generate # generate static files
  - hexo deploy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
